# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad8c958ad8fb6e46d93cc74e18183a02d5e5cea3e1ec0a6c87d00de4a5f0b35ce7f71d532eaaea5dfaa6e066774e3dbb6e291182b83108f770f3fe93d3e83579

test:
  secret_key_base: 5a8375e937906bba3c77d9dfba3a8986b44c5b4cd683bf839db293ab893ed8c40aaaf7b9fcc7b66cb1231aafb0f4f01b822249e78e6dc71b4ff2bee57c3cdcf7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
